# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby File.read('.ruby-version').strip

gem 'ddtrace', '~> 0.41'
gem 'devise_token_auth'
gem 'environment_config', '~> 1.5'
gem 'jsonapi-serializer'
gem 'mutations', '~> 0.9.1'
gem 'pg'
gem 'puma', '~> 4.3'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
gem 'sentry-raven', '~> 3.0'
gem 'tzinfo-data', '~> 1.2', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem "test-prof"
  gem 'byebug', '~> 11.1', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails', '~> 6.0'
  gem 'faker', '~> 2.12'
  gem 'rack'
  gem 'rspec-benchmark', '~> 0.6.0'
  gem 'rspec-rails', '~> 4.0'
  gem 'shoulda-matchers', '~> 4.3'
  gem 'simplecov', '~> 0.19', require: false
  gem 'yaml-lint', '~> 0.0.10', require: false
end

group :development do
  gem 'activerecord-import'
  gem 'annotate', '~> 3.1'
  gem 'bullet'
  gem 'brakeman', '~> 4.10'
  gem 'bundler-audit', '~> 0.7.0'
  gem 'bundler-leak', '~> 0.2'
  gem 'crean_cop'
  gem 'rails_best_practices', '~> 1.20', require: false
  gem 'rubycritic', '~> 4.5', require: false
end
