version: '3.7'

services:
  development:
    build: 
      context: ../../backend
    restart: always
    volumes:
      - ../../backend:/app
    ports:
      - "8040:3000"
    tty: true
    stdin_open: true
    env_file:
      - ../envs/.backend.development.local
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      RAILS_LOG_TO_STDOUT: "true"
    labels:
      - traefik.http.routers.development.rule=Host(`backend.localhost`)

  test:
    build: ../../backend
    command: bundle exec rspec
    depends_on:
      timescaledb:
        condition: service_healthy
    env_file: 
      - ../envs/.backend.test.local
    tty: true
    stdin_open: true
    volumes:
      - ../../backend:/app      
    labels:
      - traefik.enable=false